import { TRPCReactProvider } from "@repo/trpc/src/react";

import "@repo/ui/css/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { dir } from "i18next";

import { languages } from "@repo/i18";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotta",
  description: "Generated by oyerinde daniel",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: string };
}): JSX.Element {
  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body className={inter.className}>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
