import { TRPCReactProvider } from "@repo/trpc/src/react";

import "@repo/ui/css/styles.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cookies } from "next/headers";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/providers/theme-provider";
import { dir } from "i18next";

import { languages, LanguagesType } from "@repo/i18n";

export async function generateStaticParams() {
  return languages.map((lng) => ({ lang: lng }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotta",
  description: "Generated by oyerinde daniel",
};

export default function RootLayout({
  children,
  params: { lng },
}: {
  children: React.ReactNode;
  params: { lng: LanguagesType };
}): JSX.Element {
  return (
    <html lang={lng} dir={dir(lng)} suppressHydrationWarning>
      <body className={cn("bg-background", inter.className)}>
        <TRPCReactProvider cookies={cookies().toString()}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            // disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
